### ISSUE TITLE
InputElement.Value bug

### ISSUE THREAD

**Issue by n9** [Saltarelle/SaltarelleWeb#12]
[InputElement.Value](https://github.com/erik-kallen/SaltarelleWeb/blob/9cc56447682698330ef46bacaba8edd379d0dfa0/Web/Generated/Html/InputElement.cs#L450) collides with [XmlNode.Value](https://github.com/erik-kallen/SaltarelleWeb/blob/9cc56447682698330ef46bacaba8edd379d0dfa0/Web/Xml/XmlNode.cs#L19). So `inputElement.Value` is compiled into `inputElement.nodeValue` instead of `inputElement.value`.

**Comment by erik-kallen** [comment]
If your element is actualy an `InputElement`, the code should work. The problem is when you do `Element el = GetEl(); string v = el.Value`.

That being said, I agree that the thing should be addressed, as it is an obvious source of hard-to-spot bug, but I'm not sure that this is the correct solution.

I'm leaning more towards removing the Xml stuff from the Web assembly, and add a completely separate tree of types in the System.Xml namespace in another library, but where each of the types have conversion operators to and from their counterparts in the System.Html namespace. I'm not sure, though

**Comment by erik-kallen** [comment]
Please take a look at the latest build and see what you think.

**Comment by n9** [comment]
Thx, seems ok.
